apps/links/urls.py
"""Links URLs"""

from django.conf.urls import include
# Django
from django.urls import path

# Local views
from apps.links import views

urlpatterns = [
    path(
        route='',
        view=views.IndexView.as_view(),
        name='index'
    ),

    path('users/', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('dashboard/', include(('apps.dashboard.urls', 'apps.dashboard'), namespace='dashboard')),
]

apps/roles/administrator/urls.py
"""Administrator URLs."""

from django.conf.urls import include
# Django
from django.urls import path

from apps.roles.administrator import views as administrator_views
# Local views
from apps.users import views as users_views

urlpatterns = [
    path(
        route='',
        view=administrator_views.AdministratorDashboardView.as_view(),
        name='administrator'
    ),

    # Profile Admin
    path(
        route='<str:username>/',
        view=users_views.UserDetailView.as_view(
            template_name='users/detail_users/detail_admin.html'
        ),
        name='detail_admin'
    ),

    path(
        route='me/update',
        view=users_views.UserUpdateProfileView.as_view(
            template_name='users/update_users/update_profile_admin.html'

        ),
        name="update_admin"
    ),

    path('users/', include([
        path(
            route='create_user/',
            view=users_views.RegisterView.as_view(
                template_name='dashboard/roles/administrator/admin_users/create_user.html'
            ),
            name='create_user'
        ),
        path(
            route='list_users/',
            view=users_views.UserListView.as_view(),
            name='list_users'
        ),
        path(
            route='update_user/<int:pk>/',
            view=users_views.user_update_view,
            name='update_user'
        )
    ])),

    # Inventory
    path('inventory/', include([
        path(
            route='create_inventory/',
            view=administrator_views.CreateInventoryView.as_view(
                template_name='dashboard/roles/administrator/inventory/create_inventory.html'
            ),
            name='create_inventory'
        ),
        path(
            route='inventory_list/',
            view=administrator_views.InventoryListView.as_view(
                template_name='dashboard/roles/administrator/inventory/inventory_list.html'
            ),
            name='inventory_list'
        ),
        path(
            route='inventory_update/<int:id>',
            view=administrator_views.InventoryUpdateView.as_view(
                template_name='dashboard/roles/administrator/inventory/update_inventory.html'
            ),
            name='inventory_update'
        ),

        path(
            route='inventory_delete/<int:id>',
            view=administrator_views.InventoryDeleteView.as_view(),
            name='inventory_delete'
        ),

        path(
            route='export/',
            view=administrator_views.export_inventory_view,
            name='export_inventory'
        )

    ])),

    # Implement
    path('implement/', include([
        path(
            route='create_implement/',
            view=administrator_views.CreateImplementView.as_view(
                template_name='dashboard/roles/administrator/inventory/implements/create_implement.html'
            ),
            name='create_implement'
        ),

        path(
            route='create_ficha_tecnica/',
            view=administrator_views.CreateFichaTecnicaView.as_view(
                template_name='dashboard/roles/administrator/inventory/ficha_tecnica/create_ficha_tecnica.html'
            ),
            name='create_ficha_tecnica'
        ),
    ])),

    # Support
    path('support/', include([
        path(
            route='create_support/',
            view=administrator_views.SupportCreateView.as_view(
                template_name='dashboard/roles/administrator/technical_support/create_support.html'
            ),
            name='create_support'
        ),
        path(
            route='list_support/',
            view=administrator_views.SupportListView.as_view(),
            name='list_support'
        )
    ])),

    # 
]

apps/roles/auxiliary/urls.py
"""Auxiliary URLs"""

# Django
from django.urls import path, include

from apps.roles.administrator import views as administrator_view
# Local views
from apps.roles.auxiliary import views
from apps.users import views as users_views

urlpatterns = [
    path(
        route='',
        view=views.AuxiliaryDashboardView.as_view(),
        name='auxiliary'
    ),

    # Auxiliary profile
    path(
        route='<str:username>/',
        view=users_views.UserDetailView.as_view(
            template_name='users/detail_users/detail_auxiliary.html'
        ),
        name='detail_auxiliary'
    ),

    # Update user
    path(
        route='me/update/',
        view=users_views.UserUpdateProfileView.as_view(
            template_name="users/update_users/update_profile_auxiliary.html"
        ),
        name='update_auxiliary'
    ),

    path('soporte/', include([
        path(
            route='create_request/',
            view=administrator_view.SupportCreateView.as_view(
                template_name='dashboard/roles/auxiliary/technical_support/create_support.html'
            ),
            name='create_support_auxiliary'
        ),
    ])),

    # Inventory General
    path('inventory/', include([
        path(
            route='inventory_list',
            view=administrator_view.InventoryListView.as_view(
                template_name='dashboard/roles/auxiliary/inventory/inventory_list.html'
            ),
            name='inventory_auxiliary'
        ),
        path(
            route='create_inventory',
            view=administrator_view.CreateInventoryView.as_view(
                template_name='dashboard/roles/auxiliary/inventory/create_inventory.html'
            ),
            name='create_inventory_auxiliary'
        ),

        path(
            route='update_inventory/<int:id>/',
            view=administrator_view.InventoryUpdateView.as_view(
                template_name='dashboard/roles/auxiliary/inventory/update_inventory.html'
            ),
            name='inventory_update_auxiliary'
        ),
    ])),

    # Implements
    path('implement/', include([
        path(
            route='create_implement/',
            view=administrator_view.CreateImplementView.as_view(
                template_name='dashboard/roles/auxiliary/inventory/implement/create_implement.html'
            ),
            name='create_implement_auxiliary'
        ),

        path(
            route='create_ficha_tecnica/',
            view=administrator_view.CreateFichaTecnicaView.as_view(
                template_name='dashboard/roles/auxiliary/inventory/ficha_tecnica/create_ficha_tecnica.html'
            ),
            name='create_ficha_tecnica_auxiliary'
        ),

    ])),
]

django_andromeda/urls.py
"""Django andromeda URls"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
# Django
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.links.urls')),
                  path('i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/roles/auxiliary/models.py
# Create your models here.

apps/roles/auxiliary/views.py
"""Auxiliary views"""

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.views.generic.base import TemplateView

from apps.links.models import TblInventario
from apps.roles.administrator.form import InventoryUpdateForm


class AuxiliaryDashboardView(LoginRequiredMixin, TemplateView):
    """Auxiliary dashboard View"""
    login_url = reverse_lazy('users:login')
    template_name = 'dashboard/roles/auxiliary/presentation/auxiliary.html'


class InventoryAuxiliaryUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    """Update inventory view"""
    form_class = InventoryUpdateForm
    queryset = TblInventario.objects.all()
    success_url = reverse_lazy('dashboard:inventory_auxiliary')

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(TblInventario, id_inventario=id_)

    def form_valid(self, form):
        return super().form_valid(form)

templates/dashboard/roles/auxiliary/inventory/create_inventory.html
{% extends 'dashboard/roles/auxiliary/layout_auxiliary/layout.html' %}
{% block content %}
    {% url 'dashboard:auxiliary' as url_dashboard %}
    {% url 'dashboard:inventory_auxiliary' as url_inventory %}
    {% url 'dashboard:create_implement_auxiliary' as url_create_implement %}

    {% include 'dashboard/common/inventory/create_inventory.html' with dashboard=url_dashboard inventory_list=url_inventory create_implement=url_create_implement%}
{% endblock %}

templates/dashboard/roles/auxiliary/inventory/inventory_list.html
{% extends "dashboard/roles/auxiliary/layout_auxiliary/layout.html" %}
{% load static %}
{% block content %}
{% load i18n %}
    <main class="content">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    {% trans 'Lista de implementos' %}
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href={% url 'dashboard:auxiliary' %}>{% trans 'Inicio' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Inventario' %}</li>
                    </ol>
                </nav>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title d-inline-block">{% trans 'Lista de implementos registrados' %}</h5>
                            <a class="btn btn-info text-white float-right"
                               href={% url 'dashboard:create_inventory_auxiliary' %}>
                                <i class="fas fa-plus mr-3"></i>{% trans 'Agregar Implemento' %}
                            </a>
                            <a class="ml-3 btn btn-outline-success" href="{% url 'dashboard:export_inventory' %}">
                                <i class="far fa-file-excel"></i>
                                {% trans 'Exportar como CSV' %}
                            </a>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div{% if message.tags %} class="alert alert-{{ message.tags }}" role="alert"
                                    {% endif %}>
                                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="table-responsive">
                                <div class="table-content">
                                    <table class="table table-striped mb-0 text-center">
                                        <thead>
                                        <tr class="main-table">
                                            <th>{% trans 'Imagen' %}</th>
                                            <th>{% trans 'Tipo de implemento' %}</th>
                                            <th>{% trans 'Numero de serie' %}</th>
                                            <th>{% trans 'Fecha de compra' %}</th>
                                            <th>{% trans 'Precio de compra' %}</th>
                                            <th>{% trans 'Estado' %}</th>
                                            <th>{% trans 'Accion' %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in inventory_list %}
                                            <tr>
                                                <td>
                                                    <img src="{{ item.tipo_implemento.ficha_tecnica.image.url }}" alt=""
                                                         class="img-fluid" width="90">
                                                </td>
                                                <td>
                                                    <a href="#">
                                                        {{ item.tipo_implemento }}
                                                    </a>
                                                </td>
                                                <td>{{ item.numero_serie }}</td>
                                                <td>{{ item.fecha_compra }}</td>
                                                <td>{{ item.precio_compra }}</td>
                                                <td>
                                                <span class="badge badge-success">
                                                    {{ item.estado_implemento }}
                                                </span>
                                                </td>
                                                <td>
                                                    <a class="btn text-secondary px-0"
                                                       href={% url 'dashboard:inventory_update_auxiliary' item.pk %}>
                                                        <i class="far fa-edit fa-lg"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/dashboard/roles/auxiliary/inventory/update_inventory.html
{% extends "dashboard/roles/auxiliary/layout_auxiliary/layout.html" %}

{% block content %}
    {% url 'dashboard:auxiliary' as url_dashboard %}
    {% url 'dashboard:inventory_auxiliary' as url_inventory %}

    {% include 'dashboard/common/inventory/update_inventory.html' with dashboard=url_dashboard inventory_list=url_inventory %}
{% endblock %}