apps/dashboard/urls.py
"""Dashboard URLs."""

from django.conf.urls import include
# Django
from django.urls import path

urlpatterns = [
    path('administrator/', include('apps.roles.administrator.urls')),
    path('auxiliary/', include('apps.roles.auxiliary.urls')),
    path('employee/', include('apps.roles.employee.urls'))
]

apps/links/urls.py
"""Links URLs"""

from django.conf.urls import include
# Django
from django.urls import path

# Local views
from apps.links import views

urlpatterns = [
    path(
        route='',
        view=views.IndexView.as_view(),
        name='index'
    ),

    path('users/', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('dashboard/', include(('apps.dashboard.urls', 'apps.dashboard'), namespace='dashboard')),
]

apps/users/urls.py
"""Users URLs"""


# Django
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views

# Local views
from apps.users import views

urlpatterns = [

    # Management
    path('', include([
        path(
            route='login/',
            view=views.login_view,
            name='login'
        ),

        path(
            route='logout/',
            view=auth_views.LogoutView.as_view(
                next_page='users:login'
            ),
            name='logout'
        ),

        path(
            route='signup/',
            view=views.RegisterView.as_view(
                template_name='users/register.html'
            ),
            name='signup'
        ),
    ])),

    # Delete user
    path(
        route='<int:id>/delete/',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),
]

django_andromeda/urls.py
"""Django andromeda URls"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
# Django
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.links.urls')),
                  path('i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/views.py
"""Andromeda views"""

# Django

apps/users/views.py
"""Users views"""
import json
import urllib.parse
import urllib.request

from django.conf import settings
# Django
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ObjectDoesNotExist
# Exception
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DeleteView,
    TemplateView,
    DetailView,
)

from apps.links.models import (
    TblPerfil,
    TblAuxiliar,
    TblEmpleado,
    TblCoordinador,

)
# Forms
from .form import (
    UserForm,
    PositionForm,
    ProfileForm,
    ImageForm,
)


class UserDeleteView(SuccessMessageMixin, DeleteView):
    """User delete view"""
    template_name = 'dashboard/roles/administrator/admin_users/delete_user.html'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(User, id=id_)

    def get_success_url(self):
        messages.success(self.request, "Usuario eliminado con exito")
        return reverse_lazy('dashboard:list_users')

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.calculated_field,
        )


class UserListView(LoginRequiredMixin, ListView):
    """Return all users registers"""
    template_name = 'dashboard/roles/administrator/admin_users/list_user.html'
    model = User
    paginate_by = 5
    context_object_name = 'user_list'


class UserDetailView(LoginRequiredMixin, DetailView):
    """Employee detail view"""
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()


class UserUpdateProfileView(LoginRequiredMixin, TemplateView):
    """User update view"""
    profile_form = ProfileForm
    image_form = ImageForm

    def post(self, request):
        post_data = request.POST or None
        file_data = request.FILES or None

        profile_form = ProfileForm(post_data, instance=request.user)
        image_form = ImageForm(post_data, file_data, instance=request.user.tblperfil)

        if profile_form.is_valid() and image_form.is_valid():
            profile_form.save()
            image_form.save()
            messages.success(request, 'Tu perfil fue actualizado con exito!')

            position = request.user.tblperfil.posicion_id

            if position == 1:
                return HttpResponseRedirect(reverse_lazy('dashboard:detail_admin', args=[request.user.username]))

            elif position == 2:
                return HttpResponseRedirect(reverse_lazy('dashboard:detail_auxiliary', args=[request.user.username]))

            else:
                return HttpResponseRedirect(reverse_lazy('dashboard:detail_employee', args=[request.user.username]))

        context = self.get_context_data(
            profile_form=profile_form,
            image_form=image_form
        )

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def user_update_view(request, pk):
    user = User.objects.get(id=pk)
    user_form = ProfileForm(instance=user)
    position_form = PositionForm(instance=user.tblperfil)

    if request.method == 'POST':
        user_form = ProfileForm(request.POST, instance=user)
        position_form = PositionForm(request.POST, instance=user.tblperfil)

        if user_form.is_valid() and position_form.is_valid():
            user_form.save()
            position_form.save()
            messages.success(request, 'Usuario actualizado con exito!')
            return redirect('dashboard:list_users')

    context = {'user_form': user_form, 'position_form': position_form}

    return render(request, 'dashboard/roles/administrator/admin_users/update_user.html', context)


def login_view(request):
    """Login view"""
    if request.method == 'POST':
        post_data = request.POST or None

        email = post_data['email']
        password = post_data['password']

        try:
            user_data = User.objects.get(username=email)
            user = authenticate(request, username=email, password=password)
            position = TblPerfil.objects.get(user_id=user_data.pk)
            position_id = position.posicion_id

            if user:
                if position_id == 1:
                    login(request, user)
                    return redirect('dashboard:administrator')

                elif position_id == 2:
                    login(request, user)
                    return redirect('dashboard:auxiliary')

                elif position_id == 3 or position_id == 4:
                    login(request, user)
                    return redirect('dashboard:employee')

                return render(request, 'users/login.html', {'error': 'El usuario no tiene registrado ningun rol'})

            return render(request, 'users/login.html', {'error': 'Correo o contraseña invalido'})

        except ObjectDoesNotExist:
            return render(request, 'users/login.html', {'error': 'Usuario invalido'})

    return render(request, 'users/login.html')


class RegisterView(TemplateView):
    """Register test"""
    user_form = UserForm()
    position_form = PositionForm()

    def post(self, request):
        post_data = request.POST or None

        user_form = UserForm(post_data)
        position_form = PositionForm(post_data)

        if user_form.is_valid() and position_form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            print(result)

            if result['success']:
                user_form.save()
                username = post_data['username']
                position = post_data['posicion']

                user = User.objects.get(username=username)
                profile = position_form.save(commit=False)
                profile.user = user
                profile.save()

                if position == '1':
                    TblCoordinador.objects.create(perfil=profile)
                elif position == '2':
                    TblAuxiliar.objects.create(perfil=profile)
                else:
                    TblEmpleado.objects.create(perfil=profile)

                messages.success(request, 'Usuario registrado con exito!')
                return HttpResponseRedirect(reverse_lazy('users:login'))
            else:
                messages.success(request, 'Invalid reCAPTCHA. Please try again.')

        context = self.get_context_data(
            form=user_form,
            position_form=position_form
        )

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/dashboard/layout/footer.html
{% load i18n %}
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-8 text-left">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">{% trans 'Soporte' %}</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">{% trans 'Privacidad' %}</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">{% trans 'Términos y Condiciones' %}</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="#">{% trans 'Contacto' %}</a>
                    </li>
                </ul>
            </div>
            <div class="col-4 text-right">
                <p class="mb-0">
                    © 2020 - <a href="#" class="text-muted">Andromeda</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/dashboard/layout/messages.html
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link userDropdown" href="#" role="button" data-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger badge-counter mt-1">7</span>
    </a>
</li>

templates/dashboard/layout/navbarLeft.html
{% load static %}
<nav id="sidebar" class="sidebar">
    <a class="sidebar-brand" href="#">
        <img src="{% static "img/logo.png" %}" alt="Andromeda">
    </a>
    <div class="sidebar-content">
        <ul class="sidebar-nav">
            <li class="sidebar-header">Home</li>
            <li class="sidebar-item active">
                <a href="{% url 'administrator' %}" class="sidebar-link" aria-expanded="false">
                    <i class="fa-fw fas fa-home"></i>
                    <span class="align-middle">Dashboard</span>
                </a>
            </li>
            <li class="sidebar-header">Administrar Usuarios</li>
            <li class="sidebar-item">
                <a href="#users" data-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-users"></i>
                    <span class="align-middle">Usuarios</span>
                </a>
                <ul id="users" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href={% url 'form_user' %}>Crear usuario</a>
                        <a class="sidebar-link" href={% url 'list_users' %}>Lista de usuarios</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="#team" data-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-user-tie"></i>
                    <span class="align-middle">Personal</span>
                </a>
                <ul id="team" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="#">Auxiliares</a>
                        <a class="sidebar-link" href="#">Control de personal</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-header">Soporte Tecnico</li>
            <li class="sidebar-item">
                <a href="#request" data-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-users"></i>
                    <span class="align-middle">Solicitudes</span>
                </a>
                <ul id="request" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="#">Crear solicitud</a>
                        <a class="sidebar-link" href="#">Control de solicitudes</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-clipboard-list"></i>
                    <span class="align-middle">Reportes</span>
                </a>
            </li>
            <li class="sidebar-header">Calendario</li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link" aria-expanded="false">
                    <i class="fa-fw fas fa-calendar-alt"></i>
                    <span class="align-middle">Calendario</span>
                </a>
            </li>
            <li class="sidebar-header">Préstamos Tecnologicos</li>
            <li class="sidebar-item">
                <a href="#prestamo" data-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-laptop"></i>
                    <span class="align-middle">Préstamos</span>
                </a>
                <ul id="prestamo" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="#">Agendar préstamo</a>
                        <a class="sidebar-link" href="#">Control de préstamos</a>
                        <a class="sidebar-link" href="#">Calendario de préstamos</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="#" class="sidebar-link collapsed" aria-expanded="false">
                    <i class="fa-fw fas fa-clipboard-list"></i>
                    <span class="align-middle">Reportes</span>
                </a>
            </li>
            <li class="sidebar-header">Inventario Tecnologico</li>
            <li class="sidebar-item">
                <a href="#inventory" data-toggle="collapse" class="sidebar-link collapsed"
                   aria-expanded="false">
                    <i class="fa-fw fas fa-boxes"></i>
                    <span class="align-middle">Inventario</span>
                </a>
                <ul id="inventory" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="#">Gestionar inventario</a>
                        <a class="sidebar-link" href="#">Agregar implemento</a>
                        <a class="sidebar-link" href="#">Consultar inventario</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-header">Mantenimiento de equipos</li>
            <li class="sidebar-item">
                <a href="#maintenance" data-toggle="collapse" class="sidebar-link collapsed"
                   aria-expanded="false">
                    <i class="fa-fw fas fa-tools"></i>
                    <span class="align-middle">Mantenimiento</span>
                </a>
                <ul id="maintenance" class="sidebar-dropdown list-unstyled collapse" data-parent="#sidebar">
                    <li class="sidebar-item">
                        <a class="sidebar-link" href="#">Gestionar mantenimientos</a>
                        <a class="sidebar-link" href="#">Agregar mantenimiento</a>
                        <a class="sidebar-link" href="#">Calendario de mantenimientos</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

templates/dashboard/layout/navbarTop.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-expand">
    <a class="sidebar-toggle d-flex mr-2">
        <i class="align-self-center fas fa-bars" onclick="openNav()"></i>
    </a>
    <form class="form-inline d-none d-sm-inline-block mb-0">
        <input class="form-control" type="text" placeholder="{% trans 'Buscar...' %}">
    </form>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <ul class="navbar-nav ml-auto">
            {% include "dashboard/common/change_language.html" %}
            {% include "dashboard/layout/notification.html" %}
            {% include "dashboard/layout/messages.html" %}
            {% include "dashboard/layout/user.html" %}
        </ul>
    </div>
</nav>
<script src="{% static 'js/main.js' %}"></script>

templates/dashboard/layout/notification.html
{% load static %}
{% load i18n %}
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link userDropdown" href="#" role="button" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell"></i>
        <span class="badge badge-danger badge-counter mt-1">3+</span>
        <div class="dropdown-menu dropdown-menu-right dropdown-lg" aria-labelledby="messages">
            <h5 class="dropdown-header text-center">{% trans 'Ultimos Mensajes' %}</h5>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
                <div class="notify-icon rounded-circle">
                    <img src="{% static 'img/coordinador.jpg' %}" alt="notify-icon"/>
                </div>
                <p class="notify-details">Robert Spark</p>
                <p class="message text-muted mb-0">
                    <small>{% trans 'Ha solicitado un nuevo préstamo' %}</small>
                </p>
            </a>
            <a class="dropdown-item" href="#">
                <div class="notify-icon rounded-circle">
                    <img src="{% static 'img/employee2.jpg' %}" alt="notify-icon"/>
                </div>
                <p class="notify-details">Andrea Matheous</p>
                <p class="message text-muted mb-0">
                    <small>{% trans 'Canceló el servicio' %}</small>
                </p>
            </a>
            <a class="dropdown-item" href="#">
                <div class="notify-icon rounded-circle">
                    <img src="{% static 'img/auxiliar1.jpeg' %}" alt="notify-icon"/>
                </div>
                <p class="notify-details">Juan Pablo</p>
                <p class="message text-muted mb-0">
                    <small>{% trans 'Completo un soporte técnico' %}</small>
                </p>
            </a>
        </div>
    </a>
</li>

templates/dashboard/layout/user.html
{% load i18n %}
<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle userDropdown" href="#" role="button" data-toggle="dropdown"
       aria-haspopup="false" aria-expanded="false">
        <span class="account-user-avatar rounded-circle">
            <img src="{{ request.user.tblperfil.picture.url }}" alt="Avatar"/>
        </span>
    </a>
    <div class="dropdown-menu dropdown-menu-right mt-2" aria-labelledby="userDropdown">
        <h5 class="dropdown-header text-center">{% trans 'Bienvenido' %}</h5>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href={{ user_detail }}>
            <i class="fa-fw fas fa-user"></i>
            <span class="align-middle">{% trans 'Perfil' %}</span>
        </a>
        <a class="dropdown-item" href="#">
            <i class="fas fa-fw fa-comments"></i>
            <span class="align-middle">{% trans 'Chats' %}</span>
        </a>
        <a class="dropdown-item" href="#">
            <i class="fas fa-fw fa-chart-pie"></i>
            <span class="align-middle">{% trans 'Reporte' %}</span>
        </a>
        <a class="dropdown-item" href="#">
            <i class="fas fa-fw fa-cogs"></i>
            <span class="align-middle">{% trans 'Configuración' %}</span>
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item text-danger" href={% url "users:logout" %}>
            <i class="fas fa-fw fa-arrow-alt-circle-right"></i>
            <span class="align-middle">{% trans 'Cerrar Sesión' %}</span>
        </a>
    </div>
</li>