apps/links/urls.py
"""Links URLs"""

from django.conf.urls import include
# Django
from django.urls import path

# Local views
from apps.links import views

urlpatterns = [
    path(
        route='',
        view=views.IndexView.as_view(),
        name='index'
    ),

    path('users/', include(('apps.users.urls', 'apps.users'), namespace='users')),
    path('dashboard/', include(('apps.dashboard.urls', 'apps.dashboard'), namespace='dashboard')),
]

apps/roles/administrator/urls.py
"""Administrator URLs."""

from django.conf.urls import include
# Django
from django.urls import path

from apps.roles.administrator import views as administrator_views
# Local views
from apps.users import views as users_views

urlpatterns = [
    path(
        route='',
        view=administrator_views.AdministratorDashboardView.as_view(),
        name='administrator'
    ),

    # Profile Admin
    path(
        route='<str:username>/',
        view=users_views.UserDetailView.as_view(
            template_name='users/detail_users/detail_admin.html'
        ),
        name='detail_admin'
    ),

    path(
        route='me/update',
        view=users_views.UserUpdateProfileView.as_view(
            template_name='users/update_users/update_profile_admin.html'

        ),
        name="update_admin"
    ),

    path('users/', include([
        path(
            route='create_user/',
            view=users_views.RegisterView.as_view(
                template_name='dashboard/roles/administrator/admin_users/create_user.html'
            ),
            name='create_user'
        ),
        path(
            route='list_users/',
            view=users_views.UserListView.as_view(),
            name='list_users'
        ),
        path(
            route='update_user/<int:pk>/',
            view=users_views.user_update_view,
            name='update_user'
        )
    ])),

    # Inventory
    path('inventory/', include([
        path(
            route='create_inventory/',
            view=administrator_views.CreateInventoryView.as_view(
                template_name='dashboard/roles/administrator/inventory/create_inventory.html'
            ),
            name='create_inventory'
        ),
        path(
            route='inventory_list/',
            view=administrator_views.InventoryListView.as_view(
                template_name='dashboard/roles/administrator/inventory/inventory_list.html'
            ),
            name='inventory_list'
        ),
        path(
            route='inventory_update/<int:id>',
            view=administrator_views.InventoryUpdateView.as_view(
                template_name='dashboard/roles/administrator/inventory/update_inventory.html'
            ),
            name='inventory_update'
        ),

        path(
            route='inventory_delete/<int:id>',
            view=administrator_views.InventoryDeleteView.as_view(),
            name='inventory_delete'
        ),

        path(
            route='export/',
            view=administrator_views.export_inventory_view,
            name='export_inventory'
        )

    ])),

    # Implement
    path('implement/', include([
        path(
            route='create_implement/',
            view=administrator_views.CreateImplementView.as_view(
                template_name='dashboard/roles/administrator/inventory/implements/create_implement.html'
            ),
            name='create_implement'
        ),

        path(
            route='create_ficha_tecnica/',
            view=administrator_views.CreateFichaTecnicaView.as_view(
                template_name='dashboard/roles/administrator/inventory/ficha_tecnica/create_ficha_tecnica.html'
            ),
            name='create_ficha_tecnica'
        ),
    ])),

    # Support
    path('support/', include([
        path(
            route='create_support/',
            view=administrator_views.SupportCreateView.as_view(
                template_name='dashboard/roles/administrator/technical_support/create_support.html'
            ),
            name='create_support'
        ),
        path(
            route='list_support/',
            view=administrator_views.SupportListView.as_view(),
            name='list_support'
        )
    ])),

    # 
]

apps/users/urls.py
"""Users URLs"""


# Django
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views

# Local views
from apps.users import views

urlpatterns = [

    # Management
    path('', include([
        path(
            route='login/',
            view=views.login_view,
            name='login'
        ),

        path(
            route='logout/',
            view=auth_views.LogoutView.as_view(
                next_page='users:login'
            ),
            name='logout'
        ),

        path(
            route='signup/',
            view=views.RegisterView.as_view(
                template_name='users/register.html'
            ),
            name='signup'
        ),
    ])),

    # Delete user
    path(
        route='<int:id>/delete/',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),
]

django_andromeda/urls.py
"""Django andromeda URls"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
# Django
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.links.urls')),
                  path('i18n/', include('django.conf.urls.i18n')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/roles/administrator/models.py
# Create your models here.

apps/roles/administrator/views.py
"""Administrator views"""
import csv

# Django
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    UpdateView,
    DeleteView,
)

# Models
from apps.links.models import (
    TblInventario,
    TblAuxiliar,
    TblEmpleado,
    TblSoporteTecnico,
)
# Forms
from .form import (
    InventoryForm,
    ImplementForm,
    FichaTecnicaForm,
    InventoryUpdateForm,
    SupportForm,
)


class AdministratorDashboardView(LoginRequiredMixin, TemplateView):
    """Administrator dashboard View"""
    login_url = reverse_lazy('users:login')
    template_name = 'dashboard/roles/administrator/presentation/administrator.html'


class InventoryDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """User delete view"""
    login_url = reverse_lazy('users:login')
    template_name = 'dashboard/roles/administrator/inventory/delete_inventory.html'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(TblInventario, id_inventario=id_)

    def get_success_url(self):
        messages.success(self.request, 'Registro eliminado con exito')
        return reverse_lazy('dashboard:inventory_list')

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.calculated_field,
        )


class CreateInventoryView(LoginRequiredMixin, TemplateView):
    """Add inventory in the data base"""
    login_url = reverse_lazy('users:login')
    form_class = InventoryForm()

    def post(self, request):
        post_data = request.POST or None
        form_class = InventoryForm(post_data)

        if form_class.is_valid():
            form_class.save()
            messages.success(request, 'Registro exitoso!')
            return HttpResponseRedirect(reverse_lazy('dashboard:inventory_list'))

        context = self.get_context_data(
            form=form_class
        )

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CreateImplementView(LoginRequiredMixin, TemplateView):
    """Add implement to inventory general"""
    login_url = reverse_lazy('user:login')
    form_class = ImplementForm()

    def post(self, request):
        post_data = request.POST or None
        form_class = ImplementForm(post_data)

        if form_class.is_valid():
            form_class.save()
            messages.success(request, 'Implemento registrado con exito')
            return HttpResponseRedirect(reverse_lazy('dashboard:create_inventory'))

        context = self.get_context_data(
            form=form_class
        )

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CreateFichaTecnicaView(LoginRequiredMixin, TemplateView):
    """Create ficha tecnica of the implement"""
    login_url = reverse_lazy('user:login')
    form_class = FichaTecnicaForm()

    def post(self, request):
        post_data = request.POST or None
        file_data = request.FILES or None

        form_class = FichaTecnicaForm(post_data, file_data)

        if form_class.is_valid():
            form_class.save()
            messages.success(request, 'Ficha tecnica registrada con exito!')
            return HttpResponseRedirect(reverse_lazy('dashboard:create_implement'))

        context = self.get_context_data(
            form=form_class
        )

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class InventoryListView(SuccessMessageMixin, LoginRequiredMixin, ListView):
    """All implement in inventory"""
    login_url = reverse_lazy('user:login')
    model = TblInventario
    paginate_by = 8
    context_object_name = 'inventory_list'


class InventoryUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    """Update inventory view"""
    form_class = InventoryUpdateForm
    queryset = TblInventario.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(TblInventario, id_inventario=id_)

    def form_valid(self, form):
        messages.success(self.request, "Inventario actualizado")
        position = self.request.user.tblperfil.posicion_id

        if position == 1:
            self.success_url = reverse_lazy('dashboard:inventory_list')
        elif position == 2:
            self.success_url = reverse_lazy('dashboard:inventory_auxiliary')

        return super().form_valid(form)


class SupportCreateView(LoginRequiredMixin, TemplateView):
    """ Create support view """
    login_url = reverse_lazy('user:login')
    form_class = SupportForm()

    def post(self, request):
        post_data = request.POST or None
        form_class = SupportForm(post_data)

        if form_class.is_valid():
            support = form_class.save(commit=False)
            auxiliar = TblAuxiliar.objects.get(id_auxiliar=1)
            empleado = TblEmpleado.objects.get(id_empleado=1)
            support.empleado = empleado
            support.auxiliar_asignado = auxiliar
            support.save()
            position = request.user.tblperfil.posicion_id
            messages.success(request, 'Soporte tecnico solicitado con exito!')

            if position == 1:
                return HttpResponseRedirect(reverse_lazy('dashboard:create_support'))

            elif position == 2:
                return HttpResponseRedirect(reverse_lazy('dashboard:create_support_auxiliary'))

            else:
                return HttpResponseRedirect(reverse_lazy('dashboard:create_support_employee'))

        context = self.get_context_data(form=form_class)
        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class SupportListView(LoginRequiredMixin, ListView):
    """ Create Support list """
    login_url = reverse_lazy('user:login')
    template_name = 'dashboard/common/support/list_support.html'
    model = TblSoporteTecnico
    paginate_by = 5
    context_object_name = 'list_support'


def export_inventory_view(request):
    """Export all inventory to CSV"""
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow([
        'Tipo Implemento', 'Numero de serie',
        'Fecha de compra', 'Precio de compra',
        'Fecha de registro en el sistema', 'Ultima modificacion en el sistema',
        'Estado del implemento', 'Usuario asignado'])

    for item in TblInventario.objects.all().values_list(
            'tipo_implemento', 'numero_serie',
            'fecha_compra', 'precio_compra',
            'fecha_creacion', 'fecha_modificacion',
            'estado_implemento', 'usuario_asignado'):
        writer.writerow(item)

    response['Content-Disposition'] = 'attachment; filename="inventario_andromeda.csv"'

    return response

templates/dashboard/roles/administrator/admin_users/create_user.html
{% extends "dashboard/roles/administrator/layout_admin/layout.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <main class="content">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    {% trans 'Crear usuario' %}
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href={% url "dashboard:administrator" %}>{% trans 'Inicio' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Crear usuario' %}</li>
                    </ol>
                </nav>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{% trans 'Crear usuario' %}</h5>
                        </div>
                        <div class="card-body">
                            <form class="col col-md-10 offset-md-1 col-lg-8 offset-lg-2 pt-3"
                                  method="POST" action="{% url 'users:signup' %}" autocomplete="off">
                                {% csrf_token %}
                                {{ form | crispy }}
                                {{ position_form|crispy }}
                                <div class="form-group pb-3">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="invalidCheck"
                                               required>
                                        <label class="form-check-label" for="invalidCheck">
                                            {% trans 'Acepto Términos de Servicio y Politicas de Privacidad' %}
                                        </label>
                                        <div class="invalid-feedback">
                                            {% trans 'Debes aceptar los Terminos y Condiciones' %}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-andromeda mt-2 mx-auto btn-block">{% trans 'Crear Usuario' %}
                                </button>
                                <a class="mt-4 btn-block btn btn-secondary" href="{% url 'dashboard:list_users' %}">{% trans 'Cancelar' %}</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/dashboard/roles/administrator/admin_users/delete_user.html
{% extends "dashboard/roles/administrator/layout_admin/layout.html" %}
{% load static %}
{% block content %}
{% load i18n %}
    <main class="content">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    {% trans 'Lista de Usuarios' %}
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href={% url "dashboard:administrator" %}>{% trans 'Inicio' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Usuarios' %}</li>
                    </ol>
                </nav>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{% trans 'Eliminar usuario' %}</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group text-center">
                                    <p>{% blocktranslate trimmed %}¿Estas seguro de eliminar a{% endblocktranslate %} "{{ user.username }}?"</p>
                                    <button type="submit" class="btn btn-danger">{% trans 'Eliminar' %}</button>
                                    <a class="btn btn-secondary" href="{% url 'dashboard:list_users' %}">{% trans 'Cancelar' %}</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/dashboard/roles/administrator/admin_users/list_user.html
{% extends "dashboard/roles/administrator/layout_admin/layout.html" %}
{% load static %}
{% load i18n %}
{% block content %}
    <main class="content">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    {% trans 'Lista de Usuarios' %}
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href={% url "dashboard:administrator" %}>{% trans 'Inicio' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Usuarios' %}</li>
                    </ol>
                </nav>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{% trans 'Usuarios Registrados' %}</h5>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div{% if message.tags %} class="alert alert-{{ message.tags }}"role="alert"
                                    {% endif %}>
                                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="user-control table-responsive">
                                <table class="table table-hover table-bordered table-striped mb-0 text-center">
                                    <thead>
                                    <tr class="main-table">
                                        <td>#</td>
                                        <td>{% trans 'Nombres' %}</td>
                                        <td>{% trans 'Apellidos' %}</td>
                                        <td>{% trans 'Correo Electronico' %}</td>
                                        <td>{% trans 'Creado' %}</td>
                                        <td>{% trans 'Perfil' %}</td>
                                        <td>{% trans 'Rol' %}</td>
                                        <td></td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in user_list %}
                                        <tr>
                                            <td>{{ user.pk }}</td>
                                            <td>{{ user.first_name }}</td>
                                            <td>{{ user.last_name }}</td>
                                            <td>{{ user.username }}</td>
                                            <td>{{ user.date_joined }}</td>
                                            <td>
                                                <a href="{% url  'dashboard:detail_admin' user.username %}">{{ user.username }}</a>
                                            </td>
                                            <td>
                                                <span class="badge badge-pill badge-info">{{ user.tblperfil.posicion }}</span>
                                            </td>
                                            {% if user == request.user %}
                                                <td>
                                                    <span class="badge badge-success">{% trans 'Usuario actual' %}</span>
                                                </td>
                                            {% else %}
                                                <td>
                                                    <a href="{% url 'dashboard:update_user' user.pk %}"
                                                       class="btn text-secondary px-0">
                                                        <i class="far fa-edit fa-lg"></i>
                                                    </a>
                                                    <a href="{% url 'users:delete' user.pk %}" class="btn">
                                                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                                                    </a>
                                                </td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% include 'dashboard/common/pagination.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/dashboard/roles/administrator/admin_users/update_user.html
{% extends "dashboard/roles/administrator/layout_admin/layout.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load i18n %}
    <main class="content">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    {% trans 'Lista de Usuarios' %}
                </h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href={% url "dashboard:administrator" %}>{% trans 'Inicio' %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans 'Usuarios' %}</li>
                    </ol>
                </nav>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{% trans 'Actualizar usuario' %}</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {{ user_form | crispy }}
                                {{ position_form | crispy }}
                                <button type="submit" class="btn btn-success btn-block">{% trans 'Actualizar' %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}